## Natural_Language_Processing

### Logistic Regression

## Import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Load and read the dataset

In [2]:
df = pd.read_csv("imdb_labelled.txt",delimiter = "\t", quoting = 3, header = None)
df.head(10)

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1
5  The rest of the movie lacks art, charm, meanin...  0
6                                Wasted two hours.    0
7  Saw the movie today and thought it was a good ...  1
8                               A bit predictable.    0
9  Loved the casting of Jimmy Buffet as the scien...  1

### Create an headers for the dataset

In [3]:
headers = ["Movie", "Liked"]

In [4]:
df.columns = headers

In [5]:
df.head(15)

Movie  Liked
0   A very, very, very slow-moving, aimless movie ...      0
1   Not sure who was more lost - the flat characte...      0
2   Attempting artiness with black & white and cle...      0
3        Very little music or anything to speak of.        0
4   The best scene in the movie was when Gerardo i...      1
5   The rest of the movie lacks art, charm, meanin...      0
6                                 Wasted two hours.        0
7   Saw the movie today and thought it was a good ...      1
8                                A bit predictable.        0
9   Loved the casting of Jimmy Buffet as the scien...      1
10               And those baby owls were adorable.        1
11  The movie showed a lot of Florida at it's best...      1
12  The Songs Were The Best And The Muppets Were S...      1
13                                  It Was So Cool.        1
14  This is a very "right on case" movie that deli...      1

In [6]:
df.sample(15)

Movie  Liked
686                      This is just a great movie.        1
162                                           Awful.        0
18   It's practically perfect in all of them – a tr...      1
620  This is a masterful piece of film-making, with...      1
651  The acting is fantastic, the stories are seaml...      1
87   The Wind and the Lion is well written and supe...      1
433  It came free with a DVD player I bought but I ...      0
213                        Ray Charles is legendary.        1
271              Up there with the best of Melville.        1
2    Attempting artiness with black & white and cle...      0
656  Very true to Shakespear, and a 'must' for all ...      1
638  I have to say that this film was excellently p...      1
133              All in all, a great disappointment.        0
693                 I advise you to look out for it.        1
413       The camera really likes her in this movie.        1

In [7]:
df.shape

(1000, 2)

## Clearning the Test

In [8]:
import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
  review = re.sub('[^a-zA-Z]', ' ', df['Movie'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\peter\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [9]:
print(corpus)

['slow move aimless movi distress drift young man', 'not sure lost flat charact audienc nearli half walk', 'attempt arti black white clever camera angl movi disappoint becam even ridicul act poor plot line almost non exist', 'littl music anyth speak', 'best scene movi gerardo tri find song keep run head', 'rest movi lack art charm mean empti work guess empti', 'wast two hour', 'saw movi today thought good effort good messag kid', 'bit predict', 'love cast jimmi buffet scienc teacher', 'babi owl ador', 'movi show lot florida best made look appeal', 'song best muppet hilari', 'cool', 'right case movi deliv everyth almost right face', 'averag act main person low budget clearli see', 'review long overdu sinc consid tale two sister singl greatest film ever made', 'put gem movi term screenplay cinematographi act post product edit direct aspect film make', 'practic perfect true masterpiec sea faux masterpiec', 'structur film easili tightli construct histori cinema', 'think film someth vital i

## Creating the Bags of Words Model

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2300)
X = cv.fit_transform(corpus).toarray()
y = df.iloc[:, -1].values

In [11]:
len(X[0])

2300

In [12]:
print(y)

[0 0 0 0 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1
 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 1 1
 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 0 1 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0
 0 0 0 0 0 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1
 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 0 0 1 1 1 

## Split the dataset into Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Train theLogistic Regression Model on the Training set

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the Test Results

In [15]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

## Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[69 17]
 [22 92]]


0.805

In [17]:
print(X_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Classification Reports

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.80      0.78        86
           1       0.84      0.81      0.83       114

    accuracy                           0.81       200
   macro avg       0.80      0.80      0.80       200
weighted avg       0.81      0.81      0.81       200



## Predictin if a single preview is positive or negative


### positive preview

###  I Loved the casting of Jimmy Buffet

In [19]:
new_review = "I Saw the movie today and thought it was a good one"
new_review = re.sub('[^a-zA-Z]', ' ', new_review)
new_review = new_review.lower()
new_review = new_review.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
new_review = ' '.join(new_review)
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)

[1]


### Negative Preview

In [20]:
new_review = "A bit predictable"
new_review = re.sub('[^a-zA-Z]', ' ', new_review)
new_review = new_review.lower()
new_review = new_review.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
new_review = ' '.join(new_review)
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)

[0]
